[package]
name = "null-desktop"
version = "1.0.0"
description = "NULL - Private Communications Platform"
authors = ["NULL Team"]
license = "UNLICENSED"
repository = ""
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0.0-rc", features = [] }

[dependencies]
tauri = { version = "2.0.0-rc", features = [] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[patch.crates-io]
vswhom-sys = { path = "./crates/vswhom-sys" }

